apiVersion: apps/v1
kind: Deployment
metadata: 
   name: app-deployment
   labels:
     app: frontendservice
spec:
   replicas: 2
   selector:
      matchLabels:
         app: frontendservice
   template:
       metadata:
         labels:
           app: frontendservice
       spec:
         containers:
           - name: frontendservice
             image: sereme98/distribuidos3:0.0.5
             livenessProbe:
                 httpGet:
                   path: /health
                   port: 8082
                 initialDelaySeconds: 5
                 periodSeconds: 5
             ports:
               - containerPort: 8082
