apiVersion: v1
kind: Service
metadata: 
    name: app-service
    labels:
       app: frontendservice
spec: 
   selector:
     app: frontendservice
   ports:
     - protocol: TCP
       port: 8082
       targetPort: 8082
       name: http
   type: LoadBalancer