apiVersion: v1
kind: Service
metadata: 
    name: app-service
    labels:
       app: frontendservice
spec: 
   selector:
     app: frontendservice
   ports:
     - protocol: TCP
       port: 7000
       targetPort: 7000
       name: http
   type: LoadBalancer