apiVersion: v1
kind: Service
metadata: 
    name: redis
    labels:
       app: db-service
spec: 
   selector:
     app: db-service
   ports:
     - protocol: TCP
       port: 6379
       targetPort: 6379