apiVersion: apps/v1
kind: Deployment
metadata: 
   name: db-deployment
spec:
   replicas: 2
   selector:
      matchLabels:
         app: db-service
   template:
       metadata:
         labels:
           app: db-service
       spec:
         containers:
           - name: redis
             image: "redis:alpine"
             ports:
               - containerPort: 6379